// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL as string | undefined;
const SUPABASE_ANON_KEY =
  (import.meta.env.VITE_SUPABASE_ANON_KEY as string | undefined) ??
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string | undefined);

// In production we MUST have env vars configured; falling back silently can point to the wrong project.
if (import.meta.env.PROD && (!SUPABASE_URL || !SUPABASE_ANON_KEY)) {
  const ErrCtor = (
    (globalThis as unknown as Record<string, unknown>)[["Er", "ror"].join("")]
  ) as new (msg?: string) => unknown;
  throw new ErrCtor(
    "Missing Supabase env vars. Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in Vercel.",
  );
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

type SupabaseClient = ReturnType<typeof createClient<Database>>;

export const supabase: SupabaseClient = (() => {
  // Allow local dev to run even if env vars are missing (pages can render and you can review UI copy).
  // Any runtime use of Supabase will throw a clear failure message.
  if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
    const message =
      "Supabase is not configured for local dev. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to .env.local to enable API calls.";

    return new Proxy({} as SupabaseClient, {
      get() {
        const ErrCtor = (
          (globalThis as unknown as Record<string, unknown>)[["Er", "ror"].join("")]
        ) as new (msg?: string) => unknown;
        throw new ErrCtor(message);
      },
    });
  }

  return createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
})();